config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :movies, dependent: :nullify


end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :client, optional: true


  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :set_clients, only: %i[ new edit create destroy update]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
    #@clients = Client.where.not(id: Movie.where.not(client_id: nil).pluck(:client_id)).pluck(:name)
    @clients = Client.all.pluck :name, :id
    @clients << ["Liberar_Pelicula", nil]
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie fue creada." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|

      if params[:movie][:client_id].nil?
        @movie.assign.attributes(movie_params.merge(client_id: nil))
      end


      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie fue actualizada." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie fue eliminada." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def set_clients
      @clients = Client.all.pluck :name, :id
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :client_id, :obs)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
	
  <tr>
    <th scope="row"><%= client.id %></th>
    <td><%= client.name %></td>
    <td><%= client.age %></td>
    <td>
    	<% if client.movies.last.present? %>
      	<%= client.movies.last %>
      <% else %>
      	Usa Nerdflix
      <% end %>	
    </td>
    <td><%= link_to "Show this client", client %></td>
    <td><%= link_to "Edit this client", edit_client_path(client) %></td>
    <td><%= button_to "Eliminar Datos", client, method: :delete, class: "rounded text-danger border-bottom border-danger" %></td>
  </tr>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class="container col-4 form-control border-2 mt-5" style="background-color: #e3f2fd;">
	<h1>Editing client</h1>

	<%= render "form", client: @client %>

	<br>

	<div>
	  <%= link_to "Show this client", @client %> |
	  <%= link_to "Back to clients", clients_path %>
	</div>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container  form-control border-2 mt-5" style="background-color: #e3f2fd;">
  <h1 class="fs-2 machine-font mt-2 mx-0 text-body-tertiary">Clients List</h1>

  <%= link_to "New client", new_client_path, class: "btn btn-primary ms-1 btn-secondary mb-3" %>

  <div id="clients">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Age</th>
          <th scope="col">Movie</th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each do |client| %>
          <%= render client %>
        <% end %>
      </tbody>
    </table>
  </div>

</div>


<div class="fs-5 machine-font mt-3 mx-0 btn border border-1" style="background-color: #002392;">
  <a class="text-white text-decoration-none" href="https://github.com/postre554/block_b">INFO</a>
</div>
<div class="fs-5 machine-font mt-3 mx-2 btn btn-warning">
  <a class="text-dark text-decoration-none" href="https://youtu.be/LUOo9q6wxHs">DOCUMENTACION</a>
</div>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<div class="container col-4 form-control border-2 mt-5" style="background-color: #e3f2fd;">
	<p style="color: green"><%= notice %></p>
<div class="fs-2 machine-font mt-2 mx-0 text-body-tertiary">
	Client
</div>
	<%= render @client %>
	<%= link_to "Back to clients", clients_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlockBuster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="/assets/estilo.css" data-turbo-track="reload" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-dark">
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script> 
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if movie.client.present? %>
    <div style="color: red">
      <p>Atenci&oacute;n : Esta pelicula ya se encuentra en arriendo por <%= movie.client.name %></p>
    </div>
  <% end %>


  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>


  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.select :client_id do %>
      <% @clients.each do |client| %>
        <% if client[1].present? && Movie.exists?(client_id: client[1]) %>
          <%= content_tag(:option, "**#{client[0]}**", value: client[1]) %>
        <% else %>
          <% if client[1].present? %>
            <%= content_tag(:option, client[0], value: client[1]) %>
          <% else %>
            <%= content_tag(:option, client[0], value: '') %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>






  <div>
    <%= form.label :obs, style: "display: block" %>
    <%= form.text_field :obs %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
  <div class="col-3 py-2 ">
    <div class="card border border-2 rounded">
      <div class="card-body">
        <h5 class="card-title"><%= movie.name %></h5>
        <%= link_to "Show this movie", movie, class: "fs-6 btn btn-secondary" %>
        <% picsum_url = "https://biggsinstitute.org/wp-content/uploads/sites/31/2018/09/200x300-155x233.png" %>
        <img class="my-3" src="<%= picsum_url %>" />
      </div>
    </div>
  </div>

app/views/movies/edit.html.erb
<div class="container  form-control border-2 mt-5" style="background-color: #e3f2fd;">
	<h1 class="fs-2 machine-font mt-2 mx-0 text-body-tertiary">Editing movie</h1>

	<%= render "form", movie: @movie %>

	<br>

	<div class="container  form-control border-2 mt-5" style="background-color: #e3f2fd;">
	  <%= link_to "Show this movie", @movie %> |
	  <%= link_to "Back to movies", movies_path %>
	</div>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container col-4 form-control border-2 mt-5" style="background-color: #e3f2fd;">
  <h1 class="fs-2 machine-font mt-2 mx-0 text-body-tertiary">Movies</h1>
  <%= link_to "New movie", new_movie_path, class: "btn btn-primary ms-1 btn-secondary mb-3 btn-sm" %>
  <div id="movies">
    <div class="row">
      <% @movies.each do |movie| %>
        <%= render movie %>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<div class="container  form-control border-2 mt-5" style="background-color: #e3f2fd;">
	<h1 class="fs-2 machine-font mt-2 mx-0 text-body-tertiary">New movie</h1>

	<%= render "form", movie: @movie %>

	<br>

	<div>
	  <%= link_to "Back to movies", movies_path %>
	</div>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>



<div class="container  form-control border-2 mt-5" style="background-color: #e3f2fd;">
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg_marca" >
  <div class="container-fluid">
    <%= link_to 'BlockBuster', root_path, class: 'text-decoration-none border border-1 pt-2 px-2 machine-font fs-2' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Clients', clients_path, class: 'fs-5 text-decoration-none machine-font navegalink mx-4'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Movies', movies_path, class: 'fs-5 text-decoration-none machine-font navegalink mx-4' %>
        </li>
    </div>
  </div>
</nav>